name: CI CD espectacular de adop

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:11
        env:
          MYSQL_DATABASE: petlove
          MYSQL_USER: jovannylg
          MYSQL_PASSWORD: lupita123
          MYSQL_ROOT_PASSWORD: rootpassword
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10.12]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m venv ~/Documents/semestre/web/PetLove/adop/.venv
          source ~/Documents/semestre/web/PetLove/adop/.venv/bin/activate
          pip install --upgrade pip
          pip install -r ~/Documents/semestre/web/PetLove/adop/requirements.txt

      - name: Run migrations
        run: |
          source ~/Documents/semestre/web/PetLove/adop/.venv/bin/activate
          python ~/Documents/semestre/web/PetLove/adop/manage.py migrate

      - name: Run tests
        run: |
          source ~/Documents/semestre/web/PetLove/adop/.venv/bin/activate
          # python ~/Documents/semestre/web/PetLove/adop/manage.py test


  deploy:
    #needs: test  # Este trabajo solo se ejecuta si el trabajo 'test' pasa
    runs-on: self-hosted

    strategy:
      max-parallel: 4
      #matrix:
        #python-version: [3.10.12]

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          clean: false

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies # Se instala gunicorn pero debiese estar dentro de requiriments.txt
        run: |
          pwd
          python3 -m venv ~/Documents/semestre/web/PetLove/adop/.venv
          source ~/Documents/semestre/web/PetLove/adop/.venv/bin/activate
          pip install --upgrade pip
          pip install -r ~/Documents/semestre/web/PetLove/adop/requirements.txt
          pip install gunicorn

      - name: Run migrations
        run: |
          source ~/Documents/semestre/web/PetLove/adop/.venv/bin/activate
          python ~/Documents/semestre/web/PetLove/adop/manage.py migrate
          python ~/Documents/semestre/web/PetLove/adop/manage.py collectstatic --noinput

      # - name: Start Gunicorn
      #   run: |
      #     source venv/bin/activate
      #     cd ./rumapp-park-back && gunicorn --bind 0.0.0.0:8000 rumapp_park_back.wsgi:application
      - name: Reset gunicorn supervisor
        run: |
          sudo supervisorctl restart all
          #sudo service supervisor restart
